var colors = require('colors');

console.log('\n____________[COLORS]____________')
console.log('black'.black)
console.log('red'.red)
console.log('green'.green)
console.log('yellow'.yellow)
console.log('blue'.blue)
console.log('magenta'.magenta)
console.log('cyan'.cyan)
console.log('white'.white)
console.log('gray'.gray)
console.log('grey'.grey)

console.log('\n__________[BACKGROUND]__________')
console.log('bgBlack'.bgBlack)
console.log('bgRed'.bgRed)
console.log('bgGreen'.bgGreen)
console.log('bgYellow'.bgYellow)
console.log('bgBlue'.bgBlue)
console.log('bgMagenta'.bgMagenta)
console.log('bgCyan'.byCyan)
console.log('bgWhite'.bgWhite)

console.log('\n____________[STYLES]____________')
console.log('reset'.reset)
console.log('bold'.bold)
console.log('dim'.dim)
console.log('italic'.italic)
console.log('underline'.underline)
console.log('inverse'.inverse)
console.log('hidden'.hidden)
console.log('strikethrough'.strikethrough)

console.log('\n____________[EXTRAS]____________')
console.log('rainbow'.rainbow)
console.log('zebra'.zebra)
console.log('america'.america)
console.log('trap'.trap)
console.log('random'.random)
